version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '20:00'
    target-branch: 'develop'
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: aws-sdk
        versions:
          - 2.833.0
          - 2.834.0
          - 2.839.0
          - 2.840.0
          - 2.841.0
          - 2.842.0
          - 2.843.0
          - 2.844.0
          - 2.845.0
          - 2.846.0
          - 2.847.0
          - 2.848.0
          - 2.849.0
          - 2.852.0
          - 2.854.0
          - 2.855.0
          - 2.856.0
          - 2.857.0
          - 2.858.0
          - 2.859.0
          - 2.860.0
          - 2.861.0
          - 2.862.0
          - 2.864.0
          - 2.865.0
          - 2.866.0
          - 2.867.0
          - 2.868.0
          - 2.869.0
          - 2.870.0
          - 2.871.0
          - 2.874.0
          - 2.875.0
          - 2.876.0
          - 2.877.0
          - 2.878.0
          - 2.879.0
          - 2.880.0
          - 2.881.0
          - 2.882.0
          - 2.883.0
          - 2.884.0
          - 2.885.0
          - 2.886.0
          - 2.887.0
          - 2.890.0
          - 2.891.0
          - 2.892.0
          - 2.893.0
          - 2.894.0
      - dependency-name: '@types/node'
        versions:
          - 14.14.22
          - 14.14.27
          - 14.14.28
          - 14.14.36
          - 14.14.37
          - 14.14.39
          - 14.14.41
          - 15.0.0
      - dependency-name: mongoose
        versions:
          - 5.12.3
          - 5.12.5
      - dependency-name: eslint-plugin-jest
        versions:
          - 24.3.2
          - 24.3.3
          - 24.3.4
          - 24.3.5
      - dependency-name: eslint
        versions:
          - 7.22.0
          - 7.23.0
          - 7.24.0
      - dependency-name: '@babel/core'
        versions:
          - 7.12.16
          - 7.12.17
          - 7.13.14
          - 7.13.15
          - 7.13.8
      - dependency-name: '@typescript-eslint/eslint-plugin'
        versions:
          - 4.16.1
          - 4.20.0
          - 4.21.0
      - dependency-name: '@typescript-eslint/parser'
        versions:
          - 4.20.0
          - 4.21.0
      - dependency-name: '@babel/cli'
        versions:
          - 7.12.16
          - 7.12.17
          - 7.13.14
      - dependency-name: node-cron
        versions:
          - 3.0.0
      - dependency-name: '@babel/preset-env'
        versions:
          - 7.13.10
          - 7.13.12
          - 7.13.8
          - 7.13.9
      - dependency-name: ts-jest
        versions:
          - 26.5.3
      - dependency-name: '@babel/plugin-transform-runtime'
        versions:
          - 7.12.15
          - 7.12.17
          - 7.13.6
          - 7.13.8
          - 7.13.9
      - dependency-name: express-quick-builder
        versions:
          - 1.0.4
      - dependency-name: socket.io
        versions:
          - 2.4.0
          - 3.1.0
          - 3.1.1
          - 3.1.2
      - dependency-name: '@babel/plugin-proposal-class-properties'
        versions:
          - 7.13.0
      - dependency-name: typescript
        versions:
          - 4.1.4
          - 4.1.5
          - 4.2.2
      - dependency-name: '@babel/preset-typescript'
        versions:
          - 7.12.16
          - 7.12.17
      - dependency-name: express-rate-limit
        versions:
          - 5.2.5
      - dependency-name: systeminformation
        versions:
          - 4.34.9
      - dependency-name: helmet
        versions:
          - 4.4.1
      - dependency-name: '@types/jest'
        versions:
          - 26.0.20
